# GAME
GAME_TITLE = "Lord Crocket"
GAME_VER = "0.18"
#IMG_STYLE = "DAWNLIKE"
IMG_STYLE = "ORYX"

# define some colors (R, G, B)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

# game settings
PLAYABLE_WIDTH = 768   # 16 * 64 or 32 * 32 or 64 * 16
PLAYABLE_HEIGHT = 768  # 16 * 48 or 32 * 24 or 64 * 12
FPS = 60
BGCOLOR = BLACK

TILESIZE_SCREEN = 24
TILESIZE_INVENTORY = 32
TILESIZE_FILE = 16

GRIDWIDTH = PLAYABLE_WIDTH / TILESIZE_SCREEN
GRIDHEIGHT = PLAYABLE_HEIGHT / TILESIZE_SCREEN

TEXT_PART_HEIGHT = 128
TEXT_PART_WIDTH = 600

GAME_HEIGHT = PLAYABLE_HEIGHT
GAME_WIDTH = PLAYABLE_WIDTH

MINIMAP_WIDTH = 60
MINIMAP_HEIGHT = 40

# Folders and files
IMG_FOLDER = 'img'
IMG_DAWNLIKE_SUB = 'dawnlike'
IMG_ORYX_SUB = 'oryx'
IMG_PIXEL_SUB = 'pixel'
IMG_ICONS = 'icons'
SOUND_FOLDER = 'sound'

FONT_FOLDER = 'font'
# FONT_NAME = 'unispace.ttf'
FONT_NAME = 'ProFontWindows.ttf'
